# Site settings
title: HakimJumari / Dev
description: HakimJumari.Dev
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Abdul Hakim
user_description: Currently a Senior Developer at BerryPay Malaysia. 
user_title: Fullstack Web and Backend Developer / Tech Enthusiast
email: jurason96@gmail.com
github_username:  hakimj96

# Google-analytics`
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
